### PR TITLE
Port to Sugargame v1.3 and fix Python3 regressions

### LINKED ISSUE #8: Activity continue to run in background due to dbus errors
The activity runs, unless sys.exit(0) is called in the can_close method.
This is the traceback on Ctrl+c
```
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sugar3/activity/activity.py", line 1336, in close
    self._do_close(skip_save)
  File "/usr/lib/python3.8/site-packages/sugar3/activity/activity.py", line 1310, in _do_close
    self._complete_close()
  File "/usr/lib/python3.8/site-packages/sugar3/activity/activity.py", line 1297, in _complete_close
    dbus.service.Object.remove_from_connection(self._bus)
  File "/usr/lib/python3.8/site-packages/dbus/service.py", line 629, in remove_from_connection
    raise LookupError('%r is not exported at a location matching '
LookupError: <sugar3.activity.activityservice.ActivityService at /org/laptop/Activity/321295e17f1acd48c5860ab42ccfa2b3ade4cdee at 0x7fb5bb864970> is not exported at a location matching (None,None)

```

### PR DESCRIPTION
**Pull request by srevinsaju**
Cherry picked @Creatune 's commits to fix Python3 port regressions. Closes #6 
Fixes #8

### CODE REVIEW

**Comment by ayushnawal** [comment]
@srevinsaju , is it giving `NameError: name 'sys' is not defined` ?

**Comment by Creatune** [comment]
You might want to import sys in activity.py. Seems to work for me.

**Comment by quozl** [comment]
can_close is meant to be advisory only, returning boolean, not call sys.exit.

**Comment by Creatune** [comment]
Please correct me if I am wrong, but the sugargame repo still seems to be in v1.2

**Comment by srevinsaju** [comment]
Thanks @Creatune , I assumed `update sugargame` commit by you fixed the Sugargame port, i wanted to give you commit authorship for that, but probably something odd happened. 

@ayushnawal that was because of missing sys import at the header, my bad. I have repushed and rebased the commits

@quozl The exit function the pygame forces to call sys.exit() As has been the previous commit https://github.com/sugarlabs/iknowIndia/pull/7/commits/95ea9c2f7201d83325b6165bff6a225217127174 ,  I tried use a boolean value as return, but #8 happens.

**Comment by quozl** [comment]
@srevinsaju, that sys.exit seemed to fix it doesn't mean it is the right fix to make.  See the Sugargame test activity for how to exit properly.  The event loop must be fixed.  Calling sys.exit bypasses any of Sugar Toolkit activity closure actions.

**Comment by srevinsaju** [comment]
Yes @quozl. The activity implements an exit button within the pygame window. If the button within pygame is called, the above stuff like sys.exit(0) is called. i tried return True, as I had been doing for quite number of activities, but the activity continues to run. On forced close, it gives #8 output. 

image
Picture of the EXIT button within the activity

**Comment by srevinsaju** [comment]
@Creatune I fixed the error which you got on https://github.com/sugarlabs/iknowIndia/pull/7/commits/17503f3f7483b6f4c20d061adb56189cab8b29eb. Please review

**Comment by quozl** [comment]
Keep working on avoiding sys.exit.  It should not be needed.

**Comment by srevinsaju** [comment]
@quozl, should i remove all instances of sys.exit() on pygame file too (conzoco.py)? IT has the same too

**Comment by quozl** [comment]
@srevinsaju, yes, sys.exit should not be used.  It was code from a long time ago when olpcgames module did not properly support Sugar Toolkit features.  See the Sugargames test activity for how to stop the activity quickly; note carefully how the event loop is constructed.

I've also posted [Ideal futures for the "I Know" Sugar activities](http://lists.sugarlabs.org/archive/sugar-devel/2020-January/057685.html) to give some guidance.

**Comment by srevinsaju** [comment]
yea, @quozl I have replied to the same, with some possible suggestions. It looks like an interesting task to complete, possibly for GSoC. I guess until that's fixed, should this PR be closed or work to be continued here?

**Comment by quozl** [comment]
I don't mind either way.  You're driving this pull request.  If you stop driving it, others can use your commits.

Work remaining; `sys.exit()` is not required by the Sugargame test activity or other activities, therefore this pull request still needs work.

Looking at code as of https://github.com/sugarlabs/iknowIndia/pull/7/commits/17503f3f7483b6f4c20d061adb56189cab8b29eb relative to the Sugargame test activity;

* [x] activity.py import of pygame is in a different position,
* [x] activity.py the call to build_toolbar is in a different position,
* [x] activity.py can_close does not return True as it should,
* [x] conozco.py calls pygame.init and pygame.display.init when it should not, (Sugargame does this in v1.2 onwards),
* [x] conozco.py main event loop is not able to be repeatedly called, as it contains some initialisation,
* [x] conozco.py contains several event loops which pump GTK and Pygame events, but they do not exit if the stop button is pressed (`if not self.running: break`), or if the Pygame QUIT event is received.

Some of these are necessary to fix to avoid sys.exit().

**Comment by srevinsaju** [comment]
@quozl conzoco with reference to iKnowIndia didn't have a toolbar, calling return True as of  https://github.com/sugarlabs/iknowIndia/pull/7/commits/95ea9c2f7201d83325b6165bff6a225217127174 would also be temporarily fine. Will make the other changes soon

**Comment by quozl** [comment]
Yes, I know it didn't have a toolbar, but it does now in 17503f3f7483b6f4c20d061adb56189cab8b29eb, and the call to build the toolbar is in a different place to the way the Sugargame test activity does it.  I don't know if this is a cause of failing to stop, and I think it is unlikely, but it was a difference worth noting.  As if you didn't use the Sugargame test activity as a reference.

**Comment by srevinsaju** [comment]
@quozl I have removed instance of sys,exit within activity.py, but I was unsuccessful in removing the sys.exit() from pygame files.

**Comment by quozl** [comment]
Thanks for asking.  What needs to happen next is that each of the six event loops in conozco.py are changed.

* each of the event loops is of the general form;
```python
while True:
    while Gtk.events_pending():
        Gtk.main_iteration()
    for event in wait_events():
        ...
```

* each should check if the user has asked to stop;
```python
while True:
    while Gtk.events_pending():
        Gtk.main_iteration()
    if not self.running:
        return
    for event in wait_events():
        ...
```

* but each event loop needs to be checked carefully to make sure that `return` is the right thing to do.

After that, each of the remaining calls to `sys.exit` can be replaced with `return`, and you can run coverage tests to make sure the code in those areas is tested.

**Comment by srevinsaju** [comment]
Lol, fixed it at last, after quite hours of debugging, came to know what indeed caused the issue of unterminating process, 

## Some background info:
Conzoco activities uses templates and all the `IKnow*`, normally comes under the Conzoco family :wink: . But however, these used a less systematic way of ending their pygame files, i.e, call `sys.exit()`. `sys.exit` terminates all the background processes and seems like nothing actually happened. But, behind the scenes, we can find poor dbus trying to remove the activity which it created in the first place, so that it doesn't loose CPU cycles and have open loopholes. 

## How was it discovered here?
This was ultimately found out when Sugar Toolbar was implemented in the ConzocoActivities and the `StopButton` couldn't terminate it.

## What changes were tried?
Trying anything from a simple `break`, `return` and finally calling `self.parent.close()` was tried. The latter is implemented but, it still gave a `LookupError`, I even assumed it might be a small bug in the `/lib/python*/..../sugar/activity/activity.py` and tried editing it, which made stuff worse, but, solution below:

## What changes were implemented?
Conzoco activities called a global function `wait_events()` at L115, at a place where literally no one would expect the error to be, the `wait_events` function does two things, (i) to optimize CPU cycles, it ticks the pygame clock. (ii) it returns the `pygame.event.get_events`. so this less intuitive piece of code, was putting the Conzoco in a while loop along with another while Loop `while 1:` which too was eagerly waiting for more events from a closed sugar window.

## Commits
https://github.com/sugarlabs/iknowIndia/pull/7/commits/aa25deb4c7c49044a21950ab4ace3f4170352056

## Similar Issues
There were issues regarding the same LookupError, which can now be fixed from the ConzocoActivity
- https://github.com/sugarlabs/iknowAmerica/issues/9 by @Aniket21Mathur
- https://github.com/sugarlabs/iknowIndia/issues/8 by @srevinsaju (:man_facepalming: )

## What next?
- Implement as a security fix for other `Iknow*` activities

**Comment by Creatune** [comment]
I got the following output when I clicked the end button after clicking any option in "Play":
https://asciinema.org/a/0yfkpPtdb1PLWBX241Y2TaJPp

**Comment by Creatune** [comment]
Let me explain clearly how to reproduce the error:
1. Choose any map.
2. Under "Play", choose any option.
3. Try clicking the "End" button on the top right of the screen. Nothing happens and the error is shown as given in the link above.
EndButtonError

**Comment by Creatune** [comment]
The End button that I am talking about is the one in the screenshot. When clicked, it also gives an event queue full error

**Comment by srevinsaju** [comment]
@Creatune , seems like sound conditional statement wasn't implemented in the first place. Reproduced it with master. Fixed on https://github.com/sugarlabs/iknowIndia/pull/7/commits/5a838a6a159f97dac48319000ce128721472e15c, but I recently found another error on StopButton press, atm, I am trying to fix that

**Comment by srevinsaju** [comment]
Yup, rebased and fixed the `StopButton` too on https://github.com/sugarlabs/iknowIndia/pull/7/commits/214050988ec7ecccd8d8a595aaf6342e29a03475. @quozl please review

**Comment by quozl** [comment]
Thanks for the research.  Reviewed source code as at d8bfe88.

* [x] the `pygame.QUIT` event is not detected in the event loops at lines 593, 670, 757, 1483, and 1663,
* [x] your new call to pump GTK events in line 818 is not protected by a conditional test like the others,
* [x] the local function `wait_events` is still present, still called by other code, and so your change to avoid it has only been partially completed.

**Comment by srevinsaju** [comment]
@quozl 
wait_events is a fundamental part of the code. It maintains the CPU and pygame clock, as only a workaround, I implemented another clock at the end of the event checking loop. Should we remove that?

**Comment by srevinsaju** [comment]
Oki, on adding pygame.QUIT to other loops, it automatically should get changed. Thanks

**Comment by quozl** [comment]
It isn't fundamental.  It's just code.  In line 922 you removed the call to wait_events, and added the pygame.clock call above at the beginning (not end) of the loop.  I think that is adequate.  But you haven't finished the change with the other event loops.  Slow down and think carefully; your response doesn't need to be quick.

**Comment by srevinsaju** [comment]
Ok @quozl tested the activity for the parts I have made changes. Hope I have not missed anything

**Comment by Creatune** [comment]
Tested. It seems to work fine. I did not get any warnings or errors. Tried to play the game but my geography skills are sub-par 😅

**Comment by quozl** [comment]
Thanks.  Reviewed.  https://github.com/sugarlabs/iknowIndia/pull/7/commits/0d022fa071a174a2eb52a363a62b86f237792b9d made it difficult to do the review (because it made the pull request [aggregate difference](https://github.com/sugarlabs/iknowIndia/pull/7/files) so much larger), and it didn't fix all the flake8 warnings anyway.  While reviewing I noticed, like in another pull request recently, how the work done by the `2to3` tool had not been properly evaluated before making a commit; there were many changes from `unicode` to `str`, which were now redundant and waste of execution time now that Python 3 does it better.  Added these as of https://github.com/sugarlabs/iknowIndia/pull/7/commits/8f92dc53b3620382510c9020ac0f389b2f1d0556 and rebased the incomplete flake8 fixes.

I think this needs a complete test.  Python Coverage can help measure the extent of the test.

**Comment by srevinsaju** [comment]
Tested, tried twice. Wasn't able to reach a coverage greater that 90% on Conzoco.py 

file | statements | missing  | excluded | coverage 
-- | -- | -- | -- | --
conozco.py | 1237 | 295 | 0 | 76%
recursos/0india/datos/0india.py | 6 | 0 | 0 | 100%
recursos/0india/datos/explorations.py | 7 | 0 | 0 | 100%
recursos/0india/datos/levels.py | 5 | 0 | 0 | 100%
recursos/4andhrapradesh/datos/4andhrapradesh.py | 8 | 0 | 0 | 100%
recursos/4goa/datos/4goa.py | 8 | 0 | 0 | 100%
recursos/4goa/datos/explorations.py | 7 | 0 | 0 | 100%
recursos/4goa/datos/levels.py | 5 | 0 | 0 | 100%
recursos/4uttarpradesh/datos/4uttarpradesh.py | 8 | 0 | 0 | 100%
recursos/comun/datos/commons.py | 10 | 0 | 0 | 100%
sugargame/__init__.py | 1 | 0 | 0 | 100%
sugargame/canvas.py | 47 | 14 | 0 | 70%
sugargame/event.py | 157 | 72 | 0 | 54%


I achieved 79% on third time, reviewing the coverage lines, I guess most of the iKnowIndia specific lines have already been tested. There are some lines where `hills` are tested across conditionals, which is not  under the scope of this PR, and not in iKnowIndia at least. I guess this PR is ready to merge. 

Here is the attached coverage files
[htmlcov.zip](https://github.com/sugarlabs/iknowIndia/files/4281267/htmlcov.zip)

@quozl @chimosky

**Comment by srevinsaju** [comment]
@quozl @chimosky Is there anything more I can do on this PR? Shall I start replicating this on other `Conzoco` Activities?

**Comment by quozl** [comment]
Thanks.  I've re-read the pull request.  I'd said "_I think this needs a complete test. Python Coverage can help measure the extent of the test._" and you have since showed us coverage of your test, but not the test itself.  I saw the coverage, and was hoping to learn your test method, but didn't reply at the time.  Sorry about that.

**Comment by srevinsaju** [comment]
As usual, I tried pressing every possible button, answering questions and getting some correct and some wrong. I have tried to move according to the code logic and did all the clicking as possible,
I may be wrong, I hope this is correct, I apologize for the delay though

**Comment by quozl** [comment]
Thanks.  That's not a test method I can do (insufficient knowledge of the geography), and we haven't had any other offers to test, so I've merged.

**Comment by srevinsaju** [comment]
I have sufficient knowledge of geography, and I have got most of them right  :sweat_smile:

**Comment by srevinsaju** [comment]
@quozl can I start recreating this PR for other conzoco activities?

**Comment by quozl** [comment]
Sure, if you like, I don't mind.

**Comment by srevinsaju** [comment]
Ok

**Pull request merged**
