### PR TITLE
Port To Python 3 [WIP]

### PR DESCRIPTION
**Pull request by Creatune**

### CODE REVIEW

**Comment by Creatune** [comment]
I will update sugargame in a bit.

**Comment by quozl** [comment]
> I will update sugargame in a bit.

Thanks!

**Comment by Creatune** [comment]
While testing this activity, the virtual machine screen completely blackens - forcing me to shutdown the whole system. I am not able to access the activity logs due to this. How can I fix this?

**Comment by Creatune** [comment]
weirdError

**Comment by Creatune** [comment]
The above is the screenshot of the vm

**Comment by quozl** [comment]
We saw that in last few weeks with [another activity](https://github.com/sugarlabs/dotsAndBoxes/pull/17).  It was caused by failure to properly port from Sugargame v1.1 to v1.2.  In this activity though, the cause may be calling pygame init or display init at the wrong time.  See the Sugargame v1.2 test sample activity for the correct usage.

**Comment by quozl** [comment]
Oh, by the way, you don't have to shut down the whole system.  You can ssh into it and kill the process.  Or you could use F6 for the Sugar Frame, or alt-tab to switch away from the activity.

**Comment by srevinsaju** [comment]
@Creatune the black screen was not because of the sugargame update, its because there was a TypeError for the code, which worked for python2. The screen was not initialized, and hence a black Screen 
```
Traceback (most recent call last):
  File "/media/HDD/repo/iknowIndia/conozco.py", line 1860, in principal
    self.loadAll()
  File "/media/HDD/repo/iknowIndia/conozco.py", line 1149, in loadAll
    self.cargarListaDirectorios()
  File "/media/HDD/repo/iknowIndia/conozco.py", line 375, in cargarListaDirectorios
    name = str(f.NAME, 'UTF-8')
TypeError: decoding str is not supported
```

I have cherry-picked your commits and added a few more changes to safe pygame closing, add some more changes and toolbar for the activity. Thanks.

@quozl please review #7

**Comment by Creatune** [comment]
Hi @srevinsaju. Should I make changes in your PR (if needed - so that we can complete this port quickly and it would be fun to collaborate with a fellow gci student)

**Comment by Creatune** [comment]
The activity works with the changes made in #7 by @srevinsaju. But it returns an odd output that says:
'Cannot load stats invalid literal for int() with base 10: '0.3333333333333''

**Comment by Creatune** [comment]
here is the terminal output:
https://asciinema.org/a/8As395rJs9jvy0Q2AvWOgfg9V

**Comment by Creatune** [comment]
iknowIndiaWorking

**Comment by srevinsaju** [comment]
@Creatune Yes, I was able to reproduce the error. Thanks

**Pull request closed without merging**
